# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: atelier2_app_mobile
description: An event sharing application.



repository: "https://github.com/AtelierIUTCharlemagne/AppFlutter"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


# To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  faker: ^2.0.0
  date_field: ^3.0.0
  dio: ^4.0.4
  validators: ^3.0.0
  flutter_map: ^0.14.0
  latlong: ^0.6.1
  json_serializable: ^4.0.2
  json_annotation: ^4.0.1
  mapbox_search_flutter: ^1.0.6+1

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  # activated in the `analysis_options.yaml` file
  flutter_lints: ^1.0.0
  
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3



# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - SampleMap.png
    - "assets/icon.png"
    - "assets/"
      #- images/a_dot_burr.jpeg
      #- images/a_dot_ham.jpeg

flutter_icons:
  android : true
  ios : true
  image_path: "assets/icon.png"

path: 
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.2"